### PR TITLE
*add blame user selection to list and history

### PR DESCRIPTION
**Pull request by colonelclick**
Hi Damien,

I really liked the default audit screen, but I wanted a user (blame) selector. Let me know if you would be interested in merging something like this. I kept the UI very simple. 

- Add a select to the list screen showing users with transactions for audited entires
- If a user is selected, filter the entity list to entities with transactions by the selected user
- If an entity is clicked, and a user is selected, you only see transactions for that user
- Add a select list to the history screen showing users with transactions for this entity 
- If a user is selected show transactions for the selected user
- Can select System/Anonymous user corresponding to transactions with blame id null
- Can select no user to remove selection and show normal data
- New UI elements are responsive, user and entity count on separate lines for phone, on same line for tablet
- Updated AuditsPager method to allow us to easily combine parameters. If you wanted to keep

p.s.
I have another idea to add start and end date pickers as well. I think with date pickers plus a blame picker, the built-in audit screen becomes very functional for the average plug & play use case!

### CODE REVIEW

**Comment by DamienHarper** [comment]
@colonelclick thanks for this contribution, I'll try this out asap, looks promising!

**Comment by colonelclick** [comment]
@DamienHarper let me know if you have any feedback, I am working on my datepicker idea soon.

**Comment by DamienHarper** [comment]
@colonelclick any news about this PR? I'd be happy to review it :)

**Comment by colonelclick** [comment]
@DamienHarper would you like me to look at updating this to be compatible with the current branch? It works pretty well, I am still using it in production. Thanks!

**Pull request closed without merging**
