### PR TITLE
Support doctrine/annotations:2.0

### LINKED ISSUE #344: Compatibility with doctrine/annotations:^2.0
[doctrine/annotations](https://github.com/doctrine/annotations) v2 was just released.

We should provide compatibility for this new version.

I'll do my best to test auditor-bundle with the new v2 this afternoon and provide a PR accordingly.

### PR DESCRIPTION
**Pull request by dmitryuk**
Partly closes #344
We need one more PR in `auditor` package

### CODE REVIEW

**Comment by dmitryuk** [comment]
@DamienHarper I see that doctrine/annotations removed in master branch,but in current version phpdoc attributes still possible to use

**Review by DamienHarper — COMMENTED** [review]
Thanks for the contribution @dmitryuk but `doctrine/annotations ^2.0` still is not installed in the tests 🤔

**Comment by dmitryuk** [comment]
@DamienHarper to install it, please make a new release of `auditor` package, because CI uses old `2.4.5` version with dependency doctrine/ annotation:"^1.8"

**Comment by DamienHarper** [comment]
@dmitryuk you're right, I completely forgot to release `auditor` beforehand. It's done now.

**Review by DamienHarper — APPROVED** [review]

**Pull request merged**
